"""add is_delete for likes

Revision ID: 1925252296b8
Revises: 3c3982f6a8e3
Create Date: 2019-10-21 14:12:19.887658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1925252296b8'
down_revision = '3c3982f6a8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'is_delete')
    # ### end Alembic commands ###
